package org.generation.italy.examples.jdbc.mine;

import java.util.List;
import java.util.Optional;

public interface FactionRepository {
    public List<Faction> getAllFactions() throws DataException;

    // i could receive a non existent faction, so Optional
    public Optional<Faction> getFactionByName(String name) throws DataException;

    public boolean updateFaction(Faction faction) throws DataException;

    // we don't return a Faction here because we will specify the ID in the object we pass,
    // it's not autogenerated in the db. In that case, if we need it, we'd need to pass an object
    // as a param and return another one, which is the same but with the ID added, like we did
    // with Citizen.
    public void createFaction(Faction faction) throws DataException;

    public boolean removeFactionByID(int id) throws DataException;
}
