package org.generation.italy.examples.model.tropico;

import jakarta.persistence.*;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.RoundingMode;

@Entity
@Table(name = "citizen")
public class Citizen implements Serializable {
    // for auto-generated primary keys, we use WRAPPER CLASSES
    // (they can be null, so it's clearer for Hibernate and the users
    // that it needs to be auto-generated by the db)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "first_name", length = 50)
    private String firstName;

    @Column(name = "last_name", length = 50)
    private String lastName;

    @Column(name = "gender", length = 1)
    private char gender;            // this is nullable, but realistically we'll always have a value

    @Column(name = "age")
    private int age;

    @Column(name = "education_level", length = 20)
    private String educationLevel;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "job_building_id")
    private Building jobBuilding;

    @Column(name = "salary", precision = 10, scale = 2)
    private BigDecimal salary;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "home_building_id")
    private Building homeBuilding;

    @Column(name = "wealth_level", length = 20)
    private String wealthLevel;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supported_faction_id")
    private Faction supportedFaction;

    @Column(name = "is_rebel")
    private Boolean isRebel;

    @Column(name = "happiness_total")
    private Integer happinessTotal;

    public Citizen() {}

    public Integer getId() {
        return id;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public char getGender() {
        return gender;
    }

    public int getAge() {
        return age;
    }

    public String getEducationLevel() {
        return educationLevel;
    }

    public Building getJobBuilding() {
        return jobBuilding;
    }

    public BigDecimal getSalary() {
        return salary;
    }

    public Building getHomeBuilding() {
        return homeBuilding;
    }

    public String getWealthLevel() {
        return wealthLevel;
    }

    public Faction getSupportedFaction() {
        return supportedFaction;
    }

    public Boolean getRebel() {
        return isRebel;
    }

    public Integer getHappinessTotal() {
        return happinessTotal;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setGender(char gender) {
        this.gender = gender;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public void setEducationLevel(String educationLevel) {
        this.educationLevel = educationLevel;
    }

    public void setJobBuilding(Building jobBuilding) {
        this.jobBuilding = jobBuilding;
    }

    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    public void setHomeBuilding(Building homeBuilding) {
        this.homeBuilding = homeBuilding;
    }

    public void setWealthLevel(String wealthLevel) {
        this.wealthLevel = wealthLevel;
    }

    public void setSupportedFaction(Faction supportedFaction) {
        this.supportedFaction = supportedFaction;
    }

    public void setRebel(Boolean rebel) {
        isRebel = rebel;
    }

    public void setHappinessTotal(Integer happinessTotal) {
        this.happinessTotal = happinessTotal;
    }

    private static BigDecimal moneyFromDouble(double value) {
        return BigDecimal.valueOf(value).setScale(2, RoundingMode.HALF_UP);
    }

    @Override
    public String toString() {
        return "Citizen{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", gender=" + gender +
                ", age=" + age +
                ", educationLevel='" + educationLevel + '\'' +
                ", jobBuilding=" + jobBuilding +
                ", salary=" + salary +
                ", homeBuilding=" + homeBuilding +
                ", wealthLevel='" + wealthLevel + '\'' +
                ", supportedFaction=" + supportedFaction +
                ", isRebel=" + isRebel +
                ", happinessTotal=" + happinessTotal +
                '}';
    }
}
